In [6]:
import pandas as pd

In [7]:
import numpy as np

In [8]:
import matplotlib.pyplot as plt

In [9]:
import cv2

### Resize image

In [10]:
india = cv2.imread(r"C:\Users\pc\Desktop\india.jpg")

In [11]:
cv2.imshow("INDIA", india )
cv2.waitKey(-1)

-1

In [12]:
india.shape

(932, 850, 3)

In [13]:
india_medium = cv2.resize(india, (500,500))

In [15]:
india_medium

array([[[117, 163, 189],
        [117, 163, 189],
        [117, 163, 189],
        ...,
        [111, 164, 189],
        [111, 164, 189],
        [111, 164, 189]],

       [[117, 163, 189],
        [117, 163, 189],
        [117, 163, 189],
        ...,
        [111, 164, 189],
        [111, 164, 189],
        [111, 164, 189]],

       [[117, 163, 189],
        [117, 163, 189],
        [117, 163, 189],
        ...,
        [111, 164, 189],
        [111, 164, 189],
        [111, 164, 189]],

       ...,

       [[255, 177,   1],
        [255, 177,   1],
        [255, 177,   1],
        ...,
        [255, 177,   1],
        [255, 177,   1],
        [255, 177,   1]],

       [[255, 177,   1],
        [255, 177,   1],
        [255, 177,   1],
        ...,
        [255, 177,   1],
        [255, 177,   1],
        [255, 177,   1]],

       [[255, 177,   1],
        [255, 177,   1],
        [255, 177,   1],
        ...,
        [255, 177,   1],
        [255, 177,   1],
        [255, 177,   1]]

In [16]:
cv2.imshow("window", india_medium)
cv2.waitKey(-1)

-1

In [17]:
india_small = cv2.resize(india, (250,250))

In [18]:
india_small

array([[[117, 163, 189],
        [117, 163, 189],
        [117, 163, 189],
        ...,
        [111, 164, 189],
        [111, 164, 189],
        [111, 164, 189]],

       [[117, 163, 189],
        [117, 163, 189],
        [117, 163, 189],
        ...,
        [111, 164, 189],
        [111, 164, 189],
        [111, 164, 189]],

       [[117, 163, 189],
        [117, 163, 189],
        [117, 163, 189],
        ...,
        [111, 164, 189],
        [111, 164, 189],
        [111, 164, 189]],

       ...,

       [[255, 177,   1],
        [255, 177,   1],
        [255, 177,   1],
        ...,
        [255, 177,   1],
        [255, 177,   1],
        [255, 177,   1]],

       [[255, 177,   1],
        [255, 177,   1],
        [255, 177,   1],
        ...,
        [255, 177,   1],
        [255, 177,   1],
        [255, 177,   1]],

       [[255, 177,   1],
        [255, 177,   1],
        [255, 177,   1],
        ...,
        [255, 177,   1],
        [255, 177,   1],
        [255, 177,   1]]

In [19]:
cv2.imshow("small", india_small)
cv2.waitKey(-1)

-1

In [21]:
cv2.imshow("INDIA", india )

cv2.imshow("window", india_medium)

cv2.imshow("small", india_small)
cv2.waitKey(-1)

-1

In [22]:
rabbit = cv2.imread(r"C:\Users\pc\Desktop\rabbit.jpg")

In [54]:
cv2.imshow("rabbit image", rabbit)
cv2.waitKey(-1)

-1

In [24]:
rabbit.shape

(512, 512, 3)

In [29]:
rabbit_large = cv2.resize(rabbit, (600,600))

In [30]:
cv2.imshow("LARGE", rabbit_large)
cv2.waitKey(-1)

-1

In [31]:
cv2.imshow("rabbit image", rabbit)

cv2.imshow("LARGE", rabbit_large)
cv2.waitKey(-1)

-1

In [32]:
cv2.imwrite("rabbit.jpg", rabbit)

True

In [33]:
cv2.imwrite("rabbit_large.jpg", rabbit_large)

True

### Flip Image

In [34]:
cv2.imshow("INDIA", india_medium)
cv2.waitKey(-1)

-1

In [36]:
india_flip_zero = cv2.flip(india_medium, 0)

In [41]:
cv2.imshow("INDIA", india_flip_zero)
cv2.waitKey(-1)

-1

In [39]:
india_flip_one = cv2.flip(india_medium, 1)

In [40]:
cv2.imshow("INDIA", india_flip_one)
cv2.waitKey(-1)

-1

In [43]:
cv2.imshow("INDIA", india_medium)
cv2.waitKey(-1)
cv2.imshow("INDIA", india_flip_zero)
cv2.waitKey(-1)
cv2.imshow("INDIA", india_flip_one)
cv2.waitKey(-1)


-1

In [46]:
cv2.imshow("INDIA1", india_medium)

cv2.imshow("INDIA2", india_flip_zero)

cv2.imshow("INDIA3", india_flip_one)
cv2.waitKey(-1)

-1

In [44]:
india_flip_two = cv2.flip(india_medium, 2)

In [50]:
cv2.imshow("INDIA4", india_flip_two)
cv2.waitKey(-1)

-1

In [48]:
india_flip_neg = cv2.flip(india_medium, -1)

In [51]:
cv2.imshow("INDIA5", india_flip_neg)
cv2.waitKey(-1)

-1

In [52]:
cv2.imshow("INDIA1", india_medium)

cv2.imshow("INDIA2", india_flip_zero)

cv2.imshow("INDIA3", india_flip_one)
cv2.imshow("INDIA5", india_flip_neg)
cv2.waitKey(-1)

-1

### Cropping

In [53]:
rabbit.shape

(512, 512, 3)

In [83]:
rabbit_crop1 = rabbit[50: 400, 120: 400]

In [84]:
cv2.imshow("CROP", rabbit_crop1)
cv2.waitKey(-1)

-1

### Plain Image

In [85]:
wimg = np.ones((512,512, 3))

In [86]:
wimg

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       ...,

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [87]:
cv2.imshow("WHITE IMAGE", wimg)
cv2.waitKey(-1)

-1

In [88]:
dimg = np.zeros(( 512,512, 3))

In [89]:
dimg

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [90]:
cv2.imshow("DARK", dimg)
cv2.waitKey(-1)

-1

In [92]:
cv2.imshow("WHITE IMAGE", wimg)
cv2.imshow("DARK", dimg)
cv2.waitKey(-1)

-1

### Rectangle

In [93]:
rect = cv2.rectangle(wimg,pt1 = (50,50), pt2 = (300,200), color = (255,0,0), thickness = 3)

In [94]:
rect

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       ...,

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [95]:
cv2.imshow("RECTANGLE", rect)
cv2.waitKey(-1)

-1