In [12]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [13]:
import tensorflow as tf

In [14]:
tf1 = tf.constant([10,20,30,40,50])

In [15]:
tf1

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([10, 20, 30, 40, 50])>

In [16]:
type(tf1)

tensorflow.python.framework.ops.EagerTensor

In [17]:
tf.zeros((3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [18]:
a = tf.zeros((3,4))

In [19]:
a

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [20]:
print(a)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [21]:
tf.print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [22]:
a.shape

TensorShape([3, 4])

In [24]:
a.ndim

2

In [25]:
a.dtype

tf.float32

In [26]:
tf.ones((4,6))

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [27]:
b = tf.ones((4,6))

In [28]:
b

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [29]:
tf.print(b)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [30]:
b.shape

TensorShape([4, 6])

In [31]:
b.dtype

tf.float32

In [32]:
import numpy as np

In [33]:
import pandas as pd

In [37]:
x1 = tf.constant(np.random.randint(1,10,(2,2)))

In [38]:
x1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 9],
       [5, 7]])>

In [40]:
y1 = tf.constant(np.random.randint(1,10,(2,2)))

In [41]:
y1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 9],
       [2, 2]])>

In [42]:
x1 + y1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 18],
       [ 7,  9]])>

In [43]:
tf.add(x1,y1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 18],
       [ 7,  9]])>

In [44]:
display(x1,y1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 9],
       [5, 7]])>

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 9],
       [2, 2]])>

In [45]:
tf.multiply(x1,y1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 81],
       [10, 14]])>

In [46]:
x1 * y1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 81],
       [10, 14]])>

In [47]:
tf.matmul(x1,y1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[48, 72],
       [39, 59]])>

In [48]:
tf.divide(x1,y1)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1.2, 1. ],
       [2.5, 3.5]])>

In [49]:
s = tf.constant(np.random.randint(10,80,(5,8)) )

In [50]:
s

<tf.Tensor: shape=(5, 8), dtype=int32, numpy=
array([[49, 43, 71, 70, 59, 46, 60, 76],
       [76, 30, 33, 53, 64, 32, 79, 49],
       [13, 19, 75, 48, 69, 22, 39, 29],
       [64, 37, 21, 46, 38, 37, 39, 19],
       [67, 16, 11, 18, 67, 33, 22, 58]])>

In [51]:
tf.print(s)

[[49 43 71 ... 46 60 76]
 [76 30 33 ... 32 79 49]
 [13 19 75 ... 22 39 29]
 [64 37 21 ... 37 39 19]
 [67 16 11 ... 33 22 58]]


In [52]:
s.shape

TensorShape([5, 8])

In [55]:
s.ndim


2

In [56]:
print(s)

tf.Tensor(
[[49 43 71 70 59 46 60 76]
 [76 30 33 53 64 32 79 49]
 [13 19 75 48 69 22 39 29]
 [64 37 21 46 38 37 39 19]
 [67 16 11 18 67 33 22 58]], shape=(5, 8), dtype=int32)


In [57]:
s

<tf.Tensor: shape=(5, 8), dtype=int32, numpy=
array([[49, 43, 71, 70, 59, 46, 60, 76],
       [76, 30, 33, 53, 64, 32, 79, 49],
       [13, 19, 75, 48, 69, 22, 39, 29],
       [64, 37, 21, 46, 38, 37, 39, 19],
       [67, 16, 11, 18, 67, 33, 22, 58]])>

In [58]:
tf.argmax(s)

<tf.Tensor: shape=(8,), dtype=int64, numpy=array([1, 0, 2, 0, 2, 0, 1, 0], dtype=int64)>

In [59]:
tf.argmax(s, axis =1 )

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([7, 6, 2, 0, 0], dtype=int64)>

In [60]:
tf.argmin(s)

<tf.Tensor: shape=(8,), dtype=int64, numpy=array([2, 4, 4, 4, 3, 2, 4, 3], dtype=int64)>

In [61]:
tf.argmin(s, axis= 1)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 1, 0, 7, 2], dtype=int64)>

In [62]:
from tensorflow.keras.layers import Flatten,Dense

In [63]:
from tensorflow.keras.models import Sequential